comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        branches:
          - main
    patch:
      default:
        target: auto
        threshold: 1%
